CFLAGS = -Wall 
all: canary
canary: canary.o

canary.o: canary.c canary.h

canary.c: canary.h

clean:
	rm -fv canary
	rm -fv canary.o


out-clean:
	rm -v "/home/barrick/work/canary/short/*"
	rm -v  "/home/barrick/work/canary/*"
